---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-cluster
spec:
  restartPolicy: Always
  hostNetwork: true
  containers:
  - name: mysqld
    image: randomcoww/mysql_cluster:latest
    args:
    - "/mysqld-entrypoint"
    - "--ndbcluster"
    - "--default_storage_engine=ndbcluster"
    - "--bind-address=0.0.0.0"
    - "--ndb-connectstring=192.168.62.237"
    env:
    - name: INIT
      value: |
        CREATE USER IF NOT EXISTS 'Keauser'@'%' IDENTIFIED BY 'xxxx789';
        GRANT ALL PRIVILEGES ON *.* TO 'Keauser'@'%' WITH GRANT OPTION;
        CREATE DATABASE IF NOT EXISTS Kea;
  - name: ndbd
    image: randomcoww/mysql_cluster:latest
    args:
    - "/ndbd-entrypoint"
    - "--ndb-connectstring=192.168.62.237"
  - name: ndb-mgmd
    image: randomcoww/mysql_cluster:latest
    args:
    - "/ndb_mgmd-entrypoint"
    env:
    - name: CONFIG
      value: |
        [ndb_mgmd default]
        datadir=/var/lib/mysql-cluster

        [ndbd default]
        NoOfReplicas=2
        DataMemory=256M
        IndexMemory=128M
        DataDir=/var/lib/mysql-cluster

        [ndb_mgmd]
        hostname=192.168.62.237

        [ndbd]
        hostname=192.168.62.238

        [ndbd]
        hostname=192.168.62.239

        [mysqld]
        hostname=192.168.62.238

        [mysqld]
        hostname=192.168.62.239
