#!/usr/bin/env bash

mysqld --initialize || true

echo -en "$INIT" > /etc/init.sql
unset INIT

## start
exec mysqld \
  --init-file=/etc/init.sql \
  --skip-name-resolve \
  --symbolic-links=0 \
  --console=true \
  "$@"
