#!/usr/bin/env bash

mysqld --initialize || true

echo -en "$INIT" > /etc/mysql/init.sql
unset INIT

echo -en "$CONFIG" > /etc/mysql/my.cnf
unset CONFIG

## start
exec mysqld \
  --init-file=/etc/mysql/init.sql \
  --skip-name-resolve \
  --console=true \
  "$@"
