---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-cluster
spec:
  restartPolicy: Always
  hostNetwork: true
  containers:
  - name: mysqld
    image: randomcoww/mysql_cluster_mysqld:latest
    args:
    - "--ndbcluster"
    - "--default_storage_engine=ndbcluster"
    - "--bind-address=0.0.0.0"
    - "--ndb-connectstring=192.168.62.237"
    env:
    - name: INIT
      value: |
        CREATE USER IF NOT EXISTS 'Keauser'@'%' IDENTIFIED BY 'xxxx789';
        GRANT ALL PRIVILEGES ON *.* TO 'Keauser'@'%' WITH GRANT OPTION;
        CREATE DATABASE IF NOT EXISTS Kea;
  - name: ndbd
    image: randomcoww/k8s-mysql_cluster_ndbd:latest
    args:
    - "--ndb-connectstring=192.168.62.237"
